
# 使用环境配置，只需 JVM 参数里加：-Dspring.profiles.active=prod

server:

  port: 8980
  servlet:
    context-path: /js

# 数据库连接
jdbc: 
  
  # Mysql 数据库配置
  type: mysql
  driver: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://82.157.6.8:3308/maoche?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
#  url: jdbc:mysql://106.52.146.81:6607/maoche?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
#  username: root
#  password: vXRXf#}4}Y}a8M)mfC66
#  testSql: SELECT 1
  url: jdbc:mysql://sh-cdb-7ulfxtus.sql.tencentcdb.com:27983/maoche?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
  username: root
  password: 4vqCz_bTo.b2Xh*.
  testSql: SELECT 1
  # 数据库连接池配置
  pool:
  
    # 初始化连接数
    init: 20
    # 最小连接数
    minIdle: 20
    # 最大连接数
    maxActive: 1000
  # 其它数据源支持读写分离
  readwriteSplitting:
    readDataSourceNames: ~
    loadBalancerAlgorithm: RANDOM

  # 多数据源名称列表，多个用逗号隔开，使用方法：@MyBatisDao(dataSourceName="ds2")
  dataSourceNames: ds2,maoche_java,maoche_product,jubo

  jubo:
    type: mysql
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cdb-7ulfxtus.sql.tencentcdb.com:27983/jubo?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
    username: root
    password: 4vqCz_bTo.b2Xh*.
    testSql: SELECT 1
    # 其它数据源支持密码加密
    encrypt:
      username: false
      password: true
    # 其它数据源支持连接池设置
    pool:
      init: 10
      minIdle: 30
      maxActive: 1000

  maoche-java:
    type: mysql
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.232.134:6608/maoche?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
    username: root
    password: vXRXf#}4}Y}a9M)mfC]8
    testSql: SELECT 1
    # 其它数据源支持密码加密
    encrypt:
      username: false
      password: true
    # 其它数据源支持连接池设置
    pool:
      init: 10
      minIdle: 30
      maxActive: 1000

  maoche_product:
    type: mysql
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cdb-7ulfxtus.sql.tencentcdb.com:27983/maoche_v2?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
    username: root
    password: 4vqCz_bTo.b2Xh*.
    testSql: SELECT 1
    # 其它数据源支持密码加密
    encrypt:
      username: false
      password: true
    # 其它数据源支持连接池设置
    pool:
      init: 10
      minIdle: 30
      maxActive: 1000


  # 多数据源配置：ds2
  ds2:
    type: mysql
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.53.235.231:6607/maoche?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
    username: root
    password: vXRXf#}4}Y}a8M)mfC]9
    testSql: SELECT 1
    # 其它数据源支持密码加密
    encrypt:
      username: false
      password: true
    # 其它数据源支持连接池设置
    pool:
      init: 20
      minIdle: 30
      maxActive: 1000
    # 其它数据源支持读写分离
    readwriteSplitting:
      readDataSourceNames: ~
      loadBalancerAlgorithm: RANDOM

# 日志配置
logging:
  config: classpath:config/logback-spring-prod.xml

spring:
  pid:
    file: /data/cat/run/application.pid

  # Redis 连接参数 （RedisProperties）
  redis:
    host: 127.0.0.1
    port: 6379
    ssl: false
    database: 0
    password: ''
    timeout: 20000
    lettuce:
      pool:
        # 最大空闲连接数
        maxIdle: 3
        # 最大活动连接数
        maxActive: 50
        maxWait: 1000

# MyBatis 相关
mybatis:

  # Mapper文件刷新线程
  mapper:
    refresh:
      enabled: false

elasticsearch:
#    ip: es-4uienven.public.tencentelasticsearch.com
#    port: 9200
#    scheme: https
#    user: elastic
#    passwd: ZRu8UqZG
  ip: 124.222.232.134
  port: 9200
  scheme: http
  user: elastic
  passwd: 24KmVo1FfoyNk65YMr8j

dtk:
  appKey: 647802ed3a2b4
  appSecret: d3198edaa629f58618015fa6685c7cac

xxl:
  job:
    enabled: false
    adminAddresses: https://task.mtxtool.com/xxl-job-admin
    appname: jeeCat
    accessToken: 2fadea384aeea2b87a77837b11e4f3d1
    address:
    ip:
    port: 28980
    logPath: logs/jeecat/job/jobhandler/
    logRetentionDays: 30

rpa:
  domain: https://cat.zhizher.com/js/a

jubo:
  domain: http://wx-ju.mtxtool.com:13086